-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, SUM(A.PRICE*B.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT A, FOOD_ORDER B
WHERE 1=1
    AND A.PRODUCT_ID = B.PRODUCT_ID
    AND SUBSTR(TO_CHAR(B.PRODUCE_DATE, 'YYYYMMDD'), 1, 6) = '202205'
GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;