-- -- 코드를 입력하세요
-- SELECT FLAVOR AS FLAVOR
-- FROM(SELECT ROW_NUMBER() OVER(ORDER BY TOTAL_ORDER) AS ROW_NUMBER,
--      FLAVOR
--      FROM (
--          SELECT
--          A.FLAVOR, 
--          (A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
--          FROM FIRST_HALF A, JULY B
--          WHERE 1=1
--          AND A.FLAVOR = B.FLAVOR
--          AND A.SHIPMENT_ID = B.SHIPMENT_ID
--          ORDER BY TOTAL_ORDER DESC
--      )
-- )
-- WHERE ROW_NUMBER < 4

-- SELECT FLAVOR AS FLAVOR
-- FROM(
--     SELECT ROW_NUMBER() OVER(ORDER BY TOTAL_ORDER) AS ROW_NUMBER,
--     A.FLAVOR, 
--     (A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
--     FROM(
--         SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
--         FROM JULY
--         GROUP BY FLAVOR
--     ) A, FIRST_HALF B
--     WHERE 1=1
--     AND A.FLAVOR = B.FLAVOR
-- )
-- WHERE ROW_NUMBER < 4

SELECT FLAVOR
FROM(
    SELECT A.FLAVOR, 
        (A.TOTAL_ORDER + B.TOTAL_ORDER) AS TOTAL_ORDER
    FROM(
        SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
        FROM JULY
        GROUP BY FLAVOR
    ) A, FIRST_HALF B
    WHERE 1=1
    AND A.FLAVOR = B.FLAVOR
    ORDER BY TOTAL_ORDER DESC
)
WHERE ROWNUM < 4