-- 코드를 입력하세요
SELECT
    T3.APNT_NO,
    T1.PT_NAME,
    T3.PT_NO,
    T3.MCDP_CD,
    T2.DR_NAME,
    T3.APNT_YMD
FROM APPOINTMENT T3
JOIN DOCTOR T2 ON T2.DR_ID = T3.MDDR_ID
JOIN PATIENT T1 ON T1.PT_NO = T3.PT_NO
WHERE 1=1    
    AND T3.APNT_CNCL_YMD IS NULL
    AND DATE(T3.APNT_YMD) = '20220413'
    AND T3.MCDP_CD = 'CS'
    ORDER BY T3.APNT_YMD;
    
