SELECT A.MEMBER_NAME, B.REVIEW_TEXT, TO_CHAR(B.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
FROM MEMBER_PROFILE A, REST_REVIEW B
WHERE A.MEMBER_ID = B.MEMBER_ID
  AND B.MEMBER_ID = (
      SELECT MEMBER_ID
      FROM (
          SELECT MEMBER_ID, COUNT(*) AS CNT
          FROM REST_REVIEW
          GROUP BY MEMBER_ID
          ORDER BY CNT DESC
      ) C
      WHERE ROWNUM = 1
  )
ORDER BY B.REVIEW_DATE ASC, B.REVIEW_TEXT ASC
